In [89]:
#Introduction to Numpy
import numpy as np
import pickle

array=np.array([1,2,3,4,5])
print(array)
print(type(array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [90]:
array1=np.array('A')
print(array1.ndim)
print(array1.shape)
#one dimensional array
array2=np.array([1,2,3])
print(array2.ndim)
print(array2.shape)
#two dimensionad array
array3=np.array([[1,2,3],
                 [2,3,4],
                 [3,4,5]
                 ])
print(array3.ndim)
print(array3.shape)


0
()
1
(3,)
2
(3, 3)


In [91]:
#three dimensional array
array4=np.array([[[1,2,3],[2,3,4],[3,4,5]]])
print("Dimension::",array4.ndim)
print("Shape::",array4.shape)
print("Info memo::",array4.flags)
print("Stride",array4.strides)
print("Data",array4.data)
print("size::",array4.size)
print("Itemsize",array4.itemsize)
print("Byte::",array4.nbytes)
print("Base::",array4.base)

# x=array4.shape(2,3)
# print(x)


Dimension:: 3
Shape:: (1, 3, 3)
Info memo::   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

Stride (72, 24, 8)
Data <memory at 0x000001F9979E6980>
size:: 9
Itemsize 8
Byte:: 72
Base:: None


In [92]:
# <!-- **all:check all elements in an array evaluate to true (non_zero)** -->
a=np.array([1,2,3,4])
print(np.all(a))
b=np.array([1,0,1])
print(np.all(b))

True
False


In [93]:
#check any element in an array is true
c=np.array([0,0,0])
print(np.any(c))
d=np.array([0,2,1,0])
print(np.any(d))

False
True


In [94]:
arg1=np.array([[1,2,3],[2,3,4]])
print(np.argmax(arg1,axis=1))
arg2=np.array([1,2,3,4])
print(np.argmax(arg2))

[2 2]
3


In [95]:
# argmin :return the index of the mininmum value
min1=np.array([1,2,3,4])
print(np.argmin(min1))
min2=np.array([[1,2,10,4],[6,7,8,9]])
print(np.argmin(min2,axis=None))
print(np.argmin(min2,axis=0))
print(np.argmin(min2,axis=1))

0
0
[0 0 1 0]
[0 0]


In [96]:
partition=np.array([[1,2,3,4],[2,3,4,5]])
print(np.argpartition(partition,1))

[[0 1 2 3]
 [0 1 2 3]]


In [97]:
#return the indeces that would sort array
argsort=np.array([[1,2,3,4],[2,3,4,5]])
print(np.argsort(argsort))

[[0 1 2 3]
 [0 1 2 3]]


In [98]:
#choose :construct new array from the  given multiple array
choice = np.array([1, 2, 3])  # All indices 0-3
chose = np.array([1, 2, 3, 4])
print(np.choose(choice, chose))

[2 3 4]


In [99]:
clp=np.array([2,3,4,5])
print(np.clip(clp,0,1))

[1 1 1 1]


In [100]:
all_opt=np.array([[3,4,5,7,56],[24,45,45,67,4]])
condition=[True,False]
print(np.compress(condition,all_opt,axis=0))
hlo=np.copy(all_opt)
print(hlo)
print(np.cumprod(all_opt))
print(np.cumsum(all_opt))
print(np.diagonal(all_opt,offset=0,axis1=0,axis2=1))
print(np.max(all_opt,axis=0))
print(np.min(all_opt,axis=(0,1)))
print(np.mean(all_opt,dtype=None))
print(np.prod(all_opt,axis=0))

[[ 3  4  5  7 56]]
[[ 3  4  5  7 56]
 [24 45 45 67  4]]
[           3           12           60          420        23520
       564480     25401600   1143072000  76585824000 306343296000]
[  3   7  12  19  75  99 144 189 256 260]
[ 3 45]
[24 45 45 67 56]
3
26.0
[ 72 180 225 469 224]


In [101]:
#conversion of array
conversion=np.array([[12,23,34,45,56],[21,32,43,54,34]])
#for the item conversion
print(conversion.item(0))
print(conversion.item(1))
print(conversion.item(1,2))
#convert array to list
print(conversion.tolist())
#convert the array into bytes
c_copy=np.copy(conversion)
c_byte=c_copy.tobytes()
print(c_byte)
#convert the array to datafile
conversion.tofile('data.txt',sep=",")
with open ("data.txt",'r') as f:
    print(f.read())

#use the dump to save the array as pickle file
conversion.dump("hello.pkl")
with open("hello.pkl",'r')as f1:
    print(f1.read())
#astype convert the array to another datatype
print(conversion.astype(float))
print(conversion.astype(str))
#byteswap used to convert swap the byteorder
print(conversion.byteswap())

#view - used to return different datatype or object type
print(conversion.view())
print(conversion.getfield(np.int16))
#fill is used to fill the entire array with scaler array
conversion.fill(34343)
print(conversion)

#reshape:reshape the array with same data
print("Reshape")
conversion.reshape(1,10)
print(conversion)


12
23
43
[[12, 23, 34, 45, 56], [21, 32, 43, 54, 34]]
b'\x0c\x00\x00\x00\x00\x00\x00\x00\x17\x00\x00\x00\x00\x00\x00\x00"\x00\x00\x00\x00\x00\x00\x00-\x00\x00\x00\x00\x00\x00\x008\x00\x00\x00\x00\x00\x00\x00\x15\x00\x00\x00\x00\x00\x00\x00 \x00\x00\x00\x00\x00\x00\x00+\x00\x00\x00\x00\x00\x00\x006\x00\x00\x00\x00\x00\x00\x00"\x00\x00\x00\x00\x00\x00\x00'
12,23,34,45,56,21,32,43,54,34
€cnumpy._core.multiarray
_reconstruct
qcnumpy
ndarray
qK…qc_codecs
encode
qXbqXlatin1q†qRq‡Rq	(KKK†q
cnumpy
dtype
qXi8q‰ˆ‡q
Rq(KX<qNNNJÿÿÿÿJÿÿÿÿKtqb‰hXP"-8 +6"qh†qRqtqb.
[[12. 23. 34. 45. 56.]
 [21. 32. 43. 54. 34.]]
[['12' '23' '34' '45' '56']
 ['21' '32' '43' '54' '34']]
[[ 864691128455135232 1657324662872342528 2449958197289549824
  3242591731706757120 4035225266123964416]
 [1513209474796486656 2305843009213693952 3098476543630901248
  3891110078048108544 2449958197289549824]]
[[12 23 34

In [102]:
shape=np.array([[1,6,3,6,8],[45,67,23,55,21]])
print("Shape of array::")
print(shape.reshape(1,10))
shp=np.copy(shape)
print(np.resize(shp,(2,3)))
print("transopse")
print(shape.transpose())
print("swap axes")
print(shape.swapaxes(0,1))
print("flatten example")
print(shape.flatten())
print(shape.ravel())
print(shape.squeeze())


Shape of array::
[[ 1  6  3  6  8 45 67 23 55 21]]
[[ 1  6  3]
 [ 6  8 45]]
transopse
[[ 1 45]
 [ 6 67]
 [ 3 23]
 [ 6 55]
 [ 8 21]]
swap axes
[[ 1 45]
 [ 6 67]
 [ 3 23]
 [ 6 55]
 [ 8 21]]
flatten example
[ 1  6  3  6  8 45 67 23 55 21]
[ 1  6  3  6  8 45 67 23 55 21]
[[ 1  6  3  6  8]
 [45 67 23 55 21]]


In [103]:
#universal function in numpy:
arr1=np.array([[1,2,3,4],[2,3,4,5]])
arr2=np.array([[4,3,2,1],[5,4,3,2]])
# <!-- Arithmetic operation -->
print("Addition")
print(arr1+arr2)
print(np.add(arr1,arr2))
print("Subtraction")
print(np.subtract(arr1,arr2))
print(arr1-arr2)
print("Product of Array")
print(np.multiply(arr1,arr2))
# print(np.reshape(4,2).matmul(arr1,arr2))
print(arr1*arr2)
print("Division")
print(np.divide(arr1,arr2))
print(arr1/arr2)
print("Power operation")
print(np.pow(arr1,2))
print(arr1**2)
print("modulus")
print(np.mod(arr1,4))
print(arr1%2)
print(arr1*arr2+10)
print("LogaddEmp")
print(np.logaddexp(arr1,arr2))
print("LogaddExmp base 2")
print(np.logaddexp2(arr1,arr2))
print("power wise")
print(np.power(arr1,arr2))
print("True divide")
print(np.true_divide(arr1,arr2))
print(np.floor_divide(arr1,arr2))
print("Positive")
print(np.positive(arr1))
print("Negative")
print(np.negative(arr2))



Addition
[[5 5 5 5]
 [7 7 7 7]]
[[5 5 5 5]
 [7 7 7 7]]
Subtraction
[[-3 -1  1  3]
 [-3 -1  1  3]]
[[-3 -1  1  3]
 [-3 -1  1  3]]
Product of Array
[[ 4  6  6  4]
 [10 12 12 10]]
[[ 4  6  6  4]
 [10 12 12 10]]
Division
[[0.25       0.66666667 1.5        4.        ]
 [0.4        0.75       1.33333333 2.5       ]]
[[0.25       0.66666667 1.5        4.        ]
 [0.4        0.75       1.33333333 2.5       ]]
Power operation
[[ 1  4  9 16]
 [ 4  9 16 25]]
[[ 1  4  9 16]
 [ 4  9 16 25]]
modulus
[[1 2 3 0]
 [2 3 0 1]]
[[1 0 1 0]
 [0 1 0 1]]
[[14 16 16 14]
 [20 22 22 20]]
LogaddEmp
[[4.04858735 3.31326169 3.31326169 4.04858735]
 [5.04858735 4.31326169 4.31326169 5.04858735]]
LogaddExmp base 2
[[4.169925  3.5849625 3.5849625 4.169925 ]
 [5.169925  4.5849625 4.5849625 5.169925 ]]
power wise
[[ 1  8  9  4]
 [32 81 64 25]]
True divide
[[0.25       0.66666667 1.5        4.        ]
 [0.4        0.75       1.33333333 2.5       ]]
[[0 0 1 4]
 [0 0 1 2]]
Positive
[[1 2 3 4]
 [2 3 4 5]]
Negative
[[-4 -3

In [104]:
#trignometric function 
value=np.array([0,np.pi/2,np.pi])
print(np.sin(value))
print(np.cos(value))
print(np.tan(value))


#normal function 
deg=np.array([[1,2,3,4,5],[2,3,4,5,6]])

sin_deg=np.sin(np.deg2rad(deg))
cons_deg=np.cos(np.deg2rad(deg))
tan_deg=np.tan(np.deg2rad(deg))
# Normal function 
print("normal function\n")
sin_dvalue=np.sin(sin_deg)
print(np.rad2deg(sin_dvalue))
print(np.sin(sin_deg))
print(np.cos(cons_deg))
print(np.tan(tan_deg))
#inversefunction
print("value of inverse function\n")
print(np.arcsin(sin_deg))
print(np.arccos(cons_deg))
print(np.arctan(tan_deg))

#inverse trignomertic function
print("Inverse trignometric function \n")
print(np.sinh(sin_deg))
print(np.cosh(cons_deg))
print(np.tanh(tan_deg))


[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
normal function

[[0.99989847 1.99918798 2.9972607  3.99351099 4.98733655]
 [1.99918798 2.9972607  3.99351099 4.98733655 5.9781395 ]]
[[0.01745152 0.03489241 0.05231207 0.06969992 0.08704544]
 [0.03489241 0.05231207 0.06969992 0.08704544 0.10433822]]
[[0.54043046 0.54081481 0.541455   0.54235048 0.54350044]
 [0.54081481 0.541455   0.54235048 0.54350044 0.54490384]]
[[0.01745684 0.03493497 0.05245581 0.07004101 0.08771257]
 [0.03493497 0.05245581 0.07004101 0.08771257 0.10549298]]
value of inverse function

[[0.01745329 0.03490659 0.05235988 0.06981317 0.08726646]
 [0.03490659 0.05235988 0.06981317 0.08726646 0.10471976]]
[[0.01745329 0.03490659 0.05235988 0.06981317 0.08726646]
 [0.03490659 0.05235988 0.06981317 0.08726646 0.10471976]]
[[0.01745329 0.03490659 0.05235988 0.06981317 0.08726646]
 [0.03490659 0.05235988 0.06981317 0.08726646 0.10471976]]

In [111]:
# Bitwise operation are used to perform the bit level operation
a=np.array([[1,2,3,30],[10,20,30,40]])
b=np.array([[11,12,13,14],[12,23,34,54]])

print("Bitwise and operation")
print(np.bitwise_and(a,b))
print("Bitwise or operation")
print(np.bitwise_or(a,b))
print("bitwise not")
print(np.bitwise_not(a,b))
print("shift right")
print(np.right_shift(a,2))
print("left shift")
print(np.left_shift(b,3))

Bitwise and operation
[[ 1  0  1 14]
 [ 8 20  2 32]]
Bitwise or operation
[[11 14 15 30]
 [14 23 62 62]]
bitwise not
[[ -2  -3  -4 -31]
 [-11 -21 -31 -41]]
shift right
[[ 0  0  0  7]
 [ 2  5  7 10]]
left shift
[[ -16  -24  -32 -248]
 [ -88 -168 -248 -328]]


In [115]:
#comparision function 
c1=np.array([[1,2,3],[6,5,4]])
c2=np.array([[4,5,6],[3,2,1]])
print("Greater ")
print(np.greater(c1,c2))
print("greater than")
print(np.greater_equal(c1,c2))
print("Less")
print(np.less(c1,c2))
print("less than ")
print(np.less_equal(c1,c2))
print("Equall")
print(np.equal(c1,c2))

Greater 
[[False False False]
 [ True  True  True]]
greater than
[[False False False]
 [ True  True  True]]
Less
[[ True  True  True]
 [False False False]]
less than 
[[ True  True  True]
 [False False False]]
Equall
[[False False False]
 [False False False]]


In [118]:
bool_a = np.array([True, False])
bool_b = np.array([True, True])

print("Logical and ")
print(np.logical_and(bool_a,bool_b))
print("logical or")
print(np.logical_or(bool_a,bool_b))
print("logical xor")
print(np.logical_not(bool_a,bool_b))
print("logical cor")
print(np.logical_xor(bool_a,bool_b))

Logical and 
[ True False]
logical or
[ True  True]
logical xor
[False  True]
logical cor
[ True  True]
